server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/flowops_auth
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: auth-service

jwt:
  secret: your-very-secure-secret-key-that-is-at-least-32-characters
  expiration: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html